name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_REPO: 'git@github.com:nibroos/nibros-portfolio.git'
      GIT_BRANCH: 'master'
      BUILD_DIR: 'build-${{ github.run_id }}'
      # VPS_USER: ${{ secrets.VPS_USER }}
      # VPS_HOST: ${{ secrets.VPS_HOST }}
      # VPS_DEPLOY_DIR: ${{ secrets.VPS_DEPLOY_DIR }}
      # APP_NAME: ${{ env.APP_NAME }}
      # FRONTEND_URL: ${{ env.FRONTEND_URL }}
      # DOMAIN: ${{ env.DOMAIN }}
      # DOCS_URL: ${{ env.DOCS_URL }}

    steps:
    - name: Checkout code
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_DEPLOY_DIR: ${{ secrets.VPS_DEPLOY_DIR }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/nibros_do_server
        chmod 600 ~/.ssh/nibros_do_server
        ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts

        cd /var/www
        mkdir -p ${{ env.BUILD_DIR }}
        cd ${{ env.BUILD_DIR }}
        git clone ${{ env.GIT_REPO }} -b ${{ env.GIT_BRANCH }}

    - name: Install packages
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_DEPLOY_DIR: ${{ secrets.VPS_DEPLOY_DIR }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts
        curl -fsSL https://bun.sh/install | bash && \
        ln -s $HOME/.bun/bin/bun /usr/local/bin/bun

        cd /var/www
        cd ${{ env.BUILD_DIR }}
        bun install
    
    - name: Generate static files
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_DEPLOY_DIR: ${{ secrets.VPS_DEPLOY_DIR }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts
        export BUN_INSTALL="$HOME/.bun" 
        export PATH="$BUN_INSTALL/bin:$PATH"
        cd /var/www
        cd ${{ env.BUILD_DIR }}
        bun run generate
        ls -A | grep -v .output | xargs rm -rf
        mv .output/public/* ./

    - name: Copy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ env.VPS_DEPLOY_DIR }}
          cd ../
          rm -rf ${{ secrets.VPS_DEPLOY_DIR }}/*
          cp -r ${{ env.BUILD_DIR }}/* ${{ secrets.VPS_DEPLOY_DIR }}

    - name: Remove build directory
      run: |
        rm -rf ${{ env.BUILD_DIR }}