name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_REPO: 'git@github.com:nibroos/nibros-portfolio.git'
      GIT_BRANCH: 'master'
      BUILD_DIR: 'build-${{ github.run_id }}'
      # VPS_USER: ${{ secrets.VPS_USER }}
      # VPS_HOST: ${{ secrets.VPS_HOST }}
      # VPS_DEPLOY_DIR: ${{ secrets.VPS_DEPLOY_DIR }}
      # APP_NAME: ${{ env.APP_NAME }}
      # FRONTEND_URL: ${{ env.FRONTEND_URL }}
      # DOMAIN: ${{ env.DOMAIN }}
      # DOCS_URL: ${{ env.DOCS_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GIT_BRANCH }}
        script: |
          cd ${{ env.BUILD_DIR }}
          git clone ${{ env.GIT_REPO }}
          pwd
          ls -A

    - name: Install packages
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ../${{ env.VPS_DEPLOY_DIR }}
          mkdir -p ${{ env.BUILD_DIR }}
          cd ${{ env.BUILD_DIR }}
          pwd
          ls -A
          bun install
    
    - name: Generate static files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ../${{ env.VPS_DEPLOY_DIR }}
          cd ${{ env.BUILD_DIR }}
          bun run generate

    - name: Copy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ../${{ env.VPS_DEPLOY_DIR }}
          cp -r ${{ env.BUILD_DIR }}/* .

    - name: Remove build directory
      run: |
        rm -rf ${{ env.BUILD_DIR }}

    # - name: Install dependencies
    #   run: bun install

    # - name: Generate static files
    #   run: |
    #     bun run generate
    #     # check current directory location
    #     pwd
    #     # check the content of the current directory
    #     ls -A

    # - name: Clean workspace
    #   run: ls -A | grep -v .output | xargs rm -rf

    # - name: Deploy to VPS
    #   env:
    #     VPS_USER: ${{ secrets.VPS_USER }}
    #     VPS_HOST: ${{ secrets.VPS_HOST }}
    #     VPS_DEPLOY_DIR: ${{ secrets.VPS_DEPLOY_DIR }}
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #   run: |
    #     # Setup SSH
    #     mkdir -p ~/.ssh
    #     echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa

    #     # Add VPS to known_hosts to avoid host verification issues
    #     ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts

    #     # Copy files to VPS
    #     scp -r ./* $VPS_USER@$VPS_HOST:$VPS_DEPLOY_DIR
    