name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_REPO: 'git@github.com:nibroos/nibros-portfolio.git'
      GIT_BRANCH: 'master'
      BUILD_DIR: 'build-${{ github.run_id }}'
      # VPS_USER: ${{ secrets.VPS_USER }}
      # VPS_HOST: ${{ secrets.VPS_HOST }}
      # VPS_DEPLOY_DIR: ${{ secrets.VPS_DEPLOY_DIR }}
      # APP_NAME: ${{ env.APP_NAME }}
      # FRONTEND_URL: ${{ env.FRONTEND_URL }}
      # DOMAIN: ${{ env.DOMAIN }}
      # DOCS_URL: ${{ env.DOCS_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GIT_BRANCH }}

    - name: Install bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "${HOME}/.bun/bin" >> $GITHUB_PATH
        source "${HOME}/.bashrc"

    - name: Create build directory
      run: mkdir -p ${{ env.BUILD_DIR }}

    - name: Install dependencies
      run: |
        cd ${{ env.BUILD_DIR }}
        bun install

    - name: Generate static files
      run: |
        cd ${{ env.BUILD_DIR }}
        bun run generate

    - name: Clean workspace
      run: |
        cd ${{ env.BUILD_DIR }}
        ls -A | grep -v .output | xargs rm -rf

    - name: Verify build directory
      run: |
        echo "Checking contents of ${{ env.BUILD_DIR }}"
        ls -R ${{ env.BUILD_DIR }}
        
    - name: Deploy to VPS
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_DEPLOY_DIR: ${{ secrets.VPS_DEPLOY_DIR }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add VPS to known_hosts to avoid host verification issues
        ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts

        # Copy files to VPS
        scp -r ${{ env.BUILD_DIR }}/* $VPS_USER@$VPS_HOST:$VPS_DEPLOY_DIR

    - name: Clean up
      run: rm -rf ${{ env.BUILD_DIR }}