name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_REPO: 'git@github.com:nibroos/nibros-portfolio.git'
      GIT_BRANCH: 'master'
      TEMP_BUILD_DIR: '/var/www/tempbuild-${{ github.run_id }}'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

    - name: Clone repository on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p ${{ env.TEMP_BUILD_DIR }}
          cd ${{ env.TEMP_BUILD_DIR }}
          git clone ${{ env.GIT_REPO }} -b ${{ env.GIT_BRANCH }} .

    - name: Install packages
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          curl -fsSL https://bun.sh/install | bash && \
          ln -s $HOME/.bun/bin/bun /usr/local/bin/bun
          cd ${{ env.TEMP_BUILD_DIR }}
          bun install

    - name: Generate static files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ env.TEMP_BUILD_DIR }}
          bun run generate
          find . -mindepth 1 ! -regex '^./.output/public\(/.*\)?' -delete
          mv .output/public/* ./

    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf ${{ secrets.VPS_DEPLOY_DIR }}/*
          cp -r ${{ env.TEMP_BUILD_DIR }}/* ${{ secrets.VPS_DEPLOY_DIR }}

    - name: Clean up build directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf ${{ env.TEMP_BUILD_DIR }}