name: Deploy to DO

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build'

    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Update REPO
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USERNAME_STAGING }}
          key: ${{ secrets.SSH_KEY_STAGING }}
          script: |
            cd /var/www/dalim-fe/
            git stash
            git pull origin staging
      - name: Install and Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USERNAME_STAGING }}
          key: ${{ secrets.SSH_KEY_STAGING }}
          script: |
            cd /var/www/dalim-fe/
            /root/.nvm/versions/node/v18.17.1/bin/bun install
            /root/.nvm/versions/node/v18.17.1/bin/bun run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: 'Deploy'

    steps:
      - uses: actions/checkout@v3
      - name: Secrets
        run: echo "${{ secrets.SSH_KEY_STAGING }} - ${{ secrets.SSH_HOST_STAGING }} - ${{ secrets.SSH_USERNAME_STAGING }}"
      - name: Run PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USERNAME_STAGING }}
          key: ${{ secrets.SSH_KEY_STAGING }}
          script: |
            pm2 restart dalim-fe
